### ISSUE TITLE
    com.google.maps.errors.OverQueryLimitException: You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account: http://g.co/dev/maps-no-account

### ISSUE THREAD

**Issue by shubhamtunwal97** [hypertrack/uber_for_x_android#14]
I have logged into the app but after selecting the source and destination there is a blank screen and this message comes in logs:
 com.google.maps.errors.OverQueryLimitException: You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account: http://g.co/dev/maps-no-account
        at com.google.maps.DirectionsApi$Response.getError(DirectionsApi.java:74)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:289)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.internal.OkHttpPendingResult.retry(OkHttpPendingResult.java:302)
        at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:291)
        at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
        at com.google.maps.PendingResultBase.await(PendingResultBase.java:58)
        at com.consumermode.activities.BookRideActivity.getDirectionsApiResult(BookRideActivity.java:191)
        at 
com..consumermode.activities.BookRideActivity.onCreate(BookRideActivity.java:75)
        at android.app.Activity.performCreate(Activity.java:6860)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2674)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2782)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1521)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by ph4t0o0o0om** [comment]
Hi I also clone this repo but I think I have a mistakes on implementing the app. I install consumer app and driver app in separate android phone i opened first the driver app and it all done it says "finding nearest rider" but when i open my consumer app there is a TOAST MESSAGE SAY'S "No cars available" what is my error? can you please help me?

**Comment by ph4t0o0o0om** [comment]
Hey notice me

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
